Repository Planificator/PlanificatorCMD, pull requests merged in 2019-10, with the labels that each got.

#2 Task 1.2; 1.3; 1.4; + removed commented code
  PlanificatorCMD/Core/Photo.cs
  PlanificatorCMD/Core/SpeakerProfile.cs
  PlanificatorCMD/Migrations/20191030115713_First Migraton.Designer.cs
  PlanificatorCMD/Migrations/20191030115713_First Migraton.cs
  PlanificatorCMD/Migrations/PlanificatorDbContextModelSnapshot.cs
  PlanificatorCMD/Persistence/PlanificatorDbContext.cs
  PlanificatorCMD/PlanificatorCMD.csproj
  PlanificatorCMD/Program.cs
  PlanificatorCMD/appsettings.json
Labels: bug, enhancement

#6 Added new Verb for adding/creating Speaker and Photo
  PlanificatorCMD/Verbs/AddSpeakerProfileVerb.cs
  PlanificatorCMD/Verbs/IAddSpeakerVerb.cs
Labels: enhancement

#8 Bugs fixed with class SpeakerManager and SpeakerRepository. Added public access to all classes
  PlanificatorCMD/Core/Photo.cs
  PlanificatorCMD/Core/SpeakerProfile.cs
  PlanificatorCMD/ISpeakerManager.cs
  PlanificatorCMD/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/PlanificatorDbContext.cs
  PlanificatorCMD/SpeakerManager.cs
  PlanificatorCMD/SpeakerRepository.cs
Labels: bug

#9 Added new features to Validator and handling errors to Application class , the adding speaker works fine
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/App/IApplication.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Managers/ISpeakerManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Persistence/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/SpeakerRepository.cs
  PlanificatorCMD/Program.cs
  PlanificatorCMD/Properties/launchSettings.json
  PlanificatorCMD/Validators/IValidator.cs
  PlanificatorCMD/Validators/Validator.cs
  PlanificatorCMD/Verbs/AddSpeakerVerb.cs
  SpeakersPhotos/1.jpg
Labels: enhancement

#14 Created Class ShowSpeakersVerb and IShowSpeakersVerb + created option of displaying info (true - full info, false - only full name)
  PlanificatorCMD/Verbs/IShowAllSpeakersVerb.cs
  PlanificatorCMD/Verbs/ShowAllSpeakersVerb.cs
Labels: enhancement
