Repository Planificator/PlanificatorCMD, pull requests merged in 2019-11, with the labels that each got.

#20 Refactored the Validator Class ,the ShowAllSpeakers method , added class AddSpeakerVerbProcessing, DisplaySpeakers
  PlanificatorCMD.Tests/ValidatorTests.cs
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/DataProcessing/AddSpeakerVerbProcessing.cs
  PlanificatorCMD/DataProcessing/IAddSpeakerVerbProcessing.cs
  PlanificatorCMD/Managers/ISpeakerManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Utils/DisplaySpeakers.cs
  PlanificatorCMD/Utils/IDisplaySpeakers.cs
  PlanificatorCMD/Validators/AddSpeakerVerbValidator.cs
  PlanificatorCMD/Validators/IAddSpeakerVerbValidator.cs
  PlanificatorCMD/Validators/IValidator.cs
Labels: bug, enhancement

#21 "Added Test Class SpeakerManagerTests + 1 test for AddSpeakerProfile() Method"
  PlanificatorCMD.Tests/SpeakerManagerTests.cs
Labels: enhancement

#22 Added tests for SpeakerProfileMapperTests
  PlanificatorCMD.Tests/SpeakerProfileMapperTests.cs
Labels: enhancement

#23 Changed List to IEnumerable parameter in DisplaySpeakers. Added new test DisplaySpeakersTests + 2 tests for method DisplayAllSpeakers
  PlanificatorCMD.Tests/DisplaySpeakersTests.cs
  PlanificatorCMD/Utils/DisplaySpeakers.cs
  PlanificatorCMD/Utils/IDisplaySpeakers.cs
Labels: bug, enhancement

#24 Added new tests
  PlanificatorCMD.Tests/AddSpeakerVerbProcessingTests.cs
Labels: enhancement

#27 Add Presentation Verb
  PlanificatorCMD.Tests/SpeakerManagerTests.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Verbs/Add_PresentationVerb.cs
  PlanificatorCMD/Verbs/IAdd_PresentationVerb.cs
Labels: enhancement

#28 Added Tests for PresentationRepository , Updated PresentationManager and PresentationRepository
  PlanificatorCMD.Tests/PresentationManagerTests.cs
  PlanificatorCMD.Tests/PresentationRepositoryTests.cs
  PlanificatorCMD/Managers/IPresentationManager.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
Labels: bug, enhancement

#34 Added Class PresentationMapper and IPresentationMapper. Resolved Dependency in IoC Container
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Utils/IPresentationMapper.cs
  PlanificatorCMD/Utils/PresentationMapper.cs
  SpeakersPhotos/1.jpg
Labels: bug, enhancement

#35 Added new classes for ShowAllPresentations,and DisplayPresentations
  PlanificatorCMD.Tests/PresentationManagerTests.cs
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Managers/IPresentationManager.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
  PlanificatorCMD/Persistence/PlanificatorDbContext.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
  PlanificatorCMD/Utils/DisplayPresentations.cs
  PlanificatorCMD/Utils/IDisplayPresentations.cs
  PlanificatorCMD/Verbs/IShowAllPresentation.cs
  PlanificatorCMD/Verbs/ShowAllPresentation.cs
Labels: enhancement

#41 Updated PresentationMaganerTests,AddSpeakerValidatorTests,DisplayPresentations,Added Tests for AddPresentationVerbProcessing,PresentationMapper
  PlanificatorCMD.Tests/AddPresentationVerbProcessingTests.cs
  PlanificatorCMD.Tests/AddSpeakerValidatorTests.cs
  PlanificatorCMD.Tests/PresentationManagerTests.cs
  PlanificatorCMD.Tests/PresentationMapperTests.cs
  PlanificatorCMD/Utils/DisplayPresentations.cs
  SpeakersPhotos/1.jpg
Labels: enhancement

#43 Covered PresentationRepository With Tests
  PlanificatorCMD.Tests/PresentationRepositoryTests.cs
  PlanificatorCMD.Tests/PresentationRepositoryTests/PresentationRepositoryTests.cs
  PlanificatorCMD.Tests/PresentationRepositoryTests/PresentationRepositoryTestsData.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
Labels: bug, enhancement

#46 New AssignSpeakerToPresentation Verb; Updated Presentation and Speaker Managers and Repositories + bugs
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Persistence/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
  PlanificatorCMD/Persistence/SpeakerRepository.cs
  PlanificatorCMD/Utils/DisplayPresentations.cs
  PlanificatorCMD/Verbs/AddSpeakerVerb.cs
  PlanificatorCMD/Verbs/AssignSpeakerToPresentationVerb.cs
  PlanificatorCMD/Verbs/IAssignSpeakerToPresentationVerb.cs
  PlanificatorCMD/Verbs/IShowAllSpeakersVerb.cs
  PlanificatorCMD/Verbs/ShowAllPresentation.cs
  PlanificatorCMD/Verbs/ShowAllSpeakersVerb.cs
Labels: bug, enhancement

#47 Added Presentation Manager
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
Labels: enhancement

#48 Added Class AssignSpeakerToPresentationVerbProcessing + interface, Added Class AssignSpeakerToPresentationVerbValidator + interface, Expanded ISpeakerManager + IPresentationManager, Added Configuration to Ioc Container, Expanded Class Application with new field + implementation
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/DataProcessing/AssignSpeakerToPresentationVerbProcessing.cs
  PlanificatorCMD/DataProcessing/IAssignSpeakerToPresentationVerbProcessing.cs
  PlanificatorCMD/Managers/IPresentationManager.cs
  PlanificatorCMD/Managers/ISpeakerManager.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Validators/AssignSpeakerToPresentationVerbValidator.cs
  PlanificatorCMD/Validators/IAssignSpeakerToPresentationVerbValidator.cs
  PlanificatorCMD/Verbs/AssignSpeakerToPresentationVerb.cs
  PlanificatorCMD/Verbs/IAssignSpeakerToPresentationVerb.cs
Labels: bug, enhancement

#50 Changed List and IEnumarable in ICollection in classes SpeakerRepository, SpeakerManager,DisplaySpeakers + their interfaces
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Persistence/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/SpeakerRepository.cs
  PlanificatorCMD/Utils/DisplaySpeakers.cs
  PlanificatorCMD/Utils/IDisplaySpeakers.cs
Labels: Refactoring

#52 Refactored the AddSpeakerValidator class , and AddSpeakerValidatorTests, Created the ExecutionResult class
  PlanificatorCMD.Tests/AddPresentationVerbValidatorTests.cs
  PlanificatorCMD.Tests/AddSpeakerValidatorTests.cs
  PlanificatorCMD/DataProcessing/AddPresentationVerbProcessing.cs
  PlanificatorCMD/DataProcessing/AddSpeakerVerbProcessing.cs
  PlanificatorCMD/DataProcessing/AssignSpeakerToPresentationVerbProcessing.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Utils/ExecutionResult.cs
  PlanificatorCMD/Validators/AddPresentationVerbvalidator.cs
  PlanificatorCMD/Validators/AddSpeakerVerbValidator.cs
Labels: Refactoring

#57 Massive Refactoring with Display Classes
  PlanificatorCMD.Tests/DisplayPresentationsTests.cs
  PlanificatorCMD.Tests/DisplaySpeakersTests.cs
  PlanificatorCMD.Tests/PresentationManagerTests.cs
  PlanificatorCMD.Tests/PresentationRepositoryTests/PresentationRepositoryTests.cs
  PlanificatorCMD.Tests/SpeakerManagerTests.cs
  PlanificatorCMD.Tests/SpeakerRepositoryTests.cs
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Managers/IPresentationManager.cs
  PlanificatorCMD/Managers/ISpeakerManager.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
  PlanificatorCMD/Persistence/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
  PlanificatorCMD/Persistence/SpeakerRepository.cs
  PlanificatorCMD/Utils/DisplayPresentations.cs
  PlanificatorCMD/Utils/DisplaySpeakers.cs
  PlanificatorCMD/Utils/IDisplayPresentations.cs
  PlanificatorCMD/Utils/IDisplaySpeakers.cs
Labels: Refactoring, enhancement

#61 Third Refactoring. Resolved Conflicts. Replaced DbContext with Repositories in Display classes. Added tests for them + added tests for PresentationManager.
  PlanificatorCMD.Tests/DisplayPresentationsTests.cs
  PlanificatorCMD.Tests/DisplaySpeakersTests.cs
  PlanificatorCMD.Tests/PresentationManagerTests.cs
  PlanificatorCMD.Tests/SpeakerManagerTests.cs
  PlanificatorCMD.Tests/SpeakerRepositoryTests.cs
  PlanificatorCMD/App/Application.cs
  PlanificatorCMD/ContainerConfiguration/ContainerConfigurator.cs
  PlanificatorCMD/Managers/IPresentationManager.cs
  PlanificatorCMD/Managers/ISpeakerManager.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
  PlanificatorCMD/Persistence/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
  PlanificatorCMD/Persistence/SpeakerRepository.cs
  PlanificatorCMD/Utils/DisplayPresentations.cs
  PlanificatorCMD/Utils/DisplaySpeakers.cs
  PlanificatorCMD/Utils/ExecutionResult.cs
  PlanificatorCMD/Utils/IDisplayPresentations.cs
  PlanificatorCMD/Utils/IDisplaySpeakers.cs
  PlanificatorCMD/Utils/PresentationMapper.cs
  PlanificatorCMD/Utils/SpeakerProfileMapper.cs
Labels: Refactoring, enhancement

#62 Edited build.cake to exclude Migrations from code coverage
  build.cake
Labels: enhancement

#64 Covered DisplayPresentations with tests. [Achived 91.6% test coverage!]
  PlanificatorCMD.Tests/DisplayPresentationsTests.cs
  build.cake
Labels: enhancement

#65 Implemented more test for DisplaySpeakers.
  PlanificatorCMD.Tests/DisplaySpeakersTests.cs
Labels: enhancement

#72 Implementation of New Method GetPresentationById; Refactoring AssignSpeakerToPresentation; Refactor Tests
  PlanificatorCMD.Tests/AssingSpeakerTopresentationVerbProcessingTests.cs
  PlanificatorCMD.Tests/PresentationManagerTests.cs
  PlanificatorCMD.Tests/PresentationRepositoryTests/PresentationRepositoryTests.cs
  PlanificatorCMD.Tests/PresentationRepositoryTests/PresentationRepositoryTestsData.cs
  PlanificatorCMD/Core/Presentation.cs
  PlanificatorCMD/DataProcessing/AssignSpeakerToPresentationVerbProcessing.cs
  PlanificatorCMD/Managers/IPresentationManager.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Persistence/IPresentationRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
Labels: Refactoring, enhancement

#74 AsssignSpeakerToPresentationVerbProcessing and AddPresentationVerbProcessing FULLY Refactored!
  PlanificatorCMD.Tests/AddPresentationVerbProcessingTests.cs
  PlanificatorCMD.Tests/AddPresentationVerbValidatorTests.cs
  PlanificatorCMD.Tests/ApplicationsTests.cs
  PlanificatorCMD.Tests/AssignSpeakerToPresentationVerbValidatorTests.cs
  PlanificatorCMD.Tests/AssingSpeakerTopresentationVerbProcessingTests.cs
  PlanificatorCMD.Tests/PresentationMapperTests.cs
  PlanificatorCMD.Tests/SpeakerManagerTests.cs
  PlanificatorCMD/DataProcessing/AddPresentationVerbProcessing.cs
  PlanificatorCMD/DataProcessing/AssignSpeakerToPresentationVerbProcessing.cs
  PlanificatorCMD/Managers/PresentationManager.cs
  PlanificatorCMD/Managers/SpeakerManager.cs
  PlanificatorCMD/Persistence/ISpeakerRepository.cs
  PlanificatorCMD/Persistence/PresentationRepository.cs
  PlanificatorCMD/Persistence/SpeakerRepository.cs
  PlanificatorCMD/Utils/DisplayPresentations.cs
  PlanificatorCMD/Utils/DisplaySpeakers.cs
  PlanificatorCMD/Utils/IPresentationMapper.cs
  PlanificatorCMD/Utils/PresentationMapper.cs
  PlanificatorCMD/Validators/AddPresentationVerbvalidator.cs
  PlanificatorCMD/Validators/AssignSpeakerToPresentationVerbValidator.cs
  PlanificatorCMD/Validators/IAddPresentationVerbValidator.cs
  PlanificatorCMD/Validators/IAssignSpeakerToPresentationVerbValidator.cs
  PlanificatorCMD/Verbs/AddPresentationVerb.cs
  PlanificatorCMD/Verbs/AssignSpeakerToPresentationVerb.cs
  PlanificatorCMD/Verbs/IAddPresentationVerb.cs
  PlanificatorCMD/Verbs/IAssignSpeakerToPresentationVerb.cs
Labels: Refactoring, bug, enhancement

#75 New Migration, edited some foreign keys 'Restricted' on 'On cascade Delete'
  PlanificatorCMD/Migrations/PlanificatorDbContextModelSnapshot.cs
Labels: bug, enhancement

#80 Added section to update bio , company for SpeakerProfile
  Application/Managers/ISpeakerManager.cs
  Application/Managers/SpeakerManager.cs
  Domain/Core/SpeakerProfile.cs
  Planificator.Tests/Planificator.Tests.csproj
  PlanificatorMVC/Areas/Identity/Pages/Account/Manage/Index.cshtml
  PlanificatorMVC/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  PlanificatorMVC/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  PlanificatorMVC/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  PlanificatorMVC/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml
  PlanificatorMVC/Startup.cs
  appveyor.yml
Labels: enhancement
